- name: Playbook to install Jenkins
  hosts: gcp_vms
  become: true
  
  tasks:  
  - name: run script to install jenkins incl. all dependancies
    ansible.builtin.script: /home/pulan/mentoring-tf-ansible/ansible/install-jenkins.sh #works okay

  - name: ensure jenkins is installed
    apt: 
      name: jenkins
      update_cache: yes
    become: yes

  - name: start jenkins
    service:
      name: jenkins
      enabled: true
      state: started



